export const ApiErrorKeys = {
  notAuthenticated: "apiErrors.notAuthenticated",
  databaseNotConfigured: "apiErrors.databaseNotConfigured",
  general: {
    forbidden: "apiErrors.general.forbidden",
    notFound: "apiErrors.general.notFound",
    failed: "apiErrors.general.failed",
    invalid: "apiErrors.general.invalid",
  },
  auth: {
    oauth: {
      disabled: "apiErrors.auth.oauth.disabled",
      failedToGenerateUrl: "apiErrors.auth.oauth.failedToGenerateUrl",
      githubNotConfigured: "apiErrors.auth.oauth.githubNotConfigured",
      googleNotConfigured: "apiErrors.auth.oauth.googleNotConfigured",
    },
    logout: {
      failed: "apiErrors.auth.logout.failed",
    },
    verificationCode: {
      emailServiceNotConfigured: "apiErrors.auth.verificationCode.emailServiceNotConfigured",
      sendFailed: "apiErrors.auth.verificationCode.sendFailed",
    },
    me: {
      failedToGetUser: "apiErrors.auth.me.failedToGetUser",
    },
  },
  admin: {
    users: {
      failedToFetch: "apiErrors.admin.users.failedToFetch",
      userNotFound: "apiErrors.admin.users.userNotFound",
      noFieldsToUpdate: "apiErrors.admin.users.noFieldsToUpdate",
      onlySuperAdminCanModifyRoles: "apiErrors.admin.users.onlySuperAdminCanModifyRoles",
      adminCannotModifyOtherAdmins: "apiErrors.admin.users.adminCannotModifyOtherAdmins",
      failedToUpdate: "apiErrors.admin.users.failedToUpdate",
      cannotDeleteSelf: "apiErrors.admin.users.cannotDeleteSelf",
      failedToDelete: "apiErrors.admin.users.failedToDelete",
    },
    messages: {
      messageNotFound: "apiErrors.admin.messages.messageNotFound",
      alreadyRevoked: "apiErrors.admin.messages.alreadyRevoked",
      failedToFetch: "apiErrors.admin.messages.failedToFetch",
      failedToFetchSingle: "apiErrors.admin.messages.failedToFetchSingle",
      roleRequired: "apiErrors.admin.messages.roleRequired",
      statusRequired: "apiErrors.admin.messages.statusRequired",
      recipientsRequired: "apiErrors.admin.messages.recipientsRequired",
      noRecipientsFound: "apiErrors.admin.messages.noRecipientsFound",
      failedToCreate: "apiErrors.admin.messages.failedToCreate",
      failedToUpdate: "apiErrors.admin.messages.failedToUpdate",
      failedToRevoke: "apiErrors.admin.messages.failedToRevoke",
    },
    inviteCodes: {
      failedToFetch: "apiErrors.admin.inviteCodes.failedToFetch",
      invalidExpiry: "apiErrors.admin.inviteCodes.invalidExpiry",
      expiryMustBeInFuture: "apiErrors.admin.inviteCodes.expiryMustBeInFuture",
      noValid: "apiErrors.admin.inviteCodes.noValid",
      failedToImport: "apiErrors.admin.inviteCodes.failedToImport",
      failedToCreate: "apiErrors.admin.inviteCodes.failedToCreate",
      queryTokenFailed: "apiErrors.admin.inviteCodes.queryTokenFailed",
      noValidFound: "apiErrors.admin.inviteCodes.noValidFound",
      notFound: "apiErrors.admin.inviteCodes.notFound",
      alreadyUsed: "apiErrors.admin.inviteCodes.alreadyUsed",
      alreadyExpired: "apiErrors.admin.inviteCodes.alreadyExpired",
      alreadyAssigned: "apiErrors.admin.inviteCodes.alreadyAssigned",
      alreadyIssued: "apiErrors.admin.inviteCodes.alreadyIssued",
      failedToInvalidate: "apiErrors.admin.inviteCodes.failedToInvalidate",
      failedToUpdateUsage: "apiErrors.admin.inviteCodes.failedToUpdateUsage",
      failedToIssue: "apiErrors.admin.inviteCodes.failedToIssue",
      userIdRequired: "apiErrors.admin.inviteCodes.userIdRequired",
      emailRequired: "apiErrors.admin.inviteCodes.emailRequired",
      emailNotificationsDisabled: "apiErrors.admin.inviteCodes.emailNotificationsDisabled",
      alreadyDeleted: "apiErrors.admin.inviteCodes.alreadyDeleted",
      failedToDelete: "apiErrors.admin.inviteCodes.failedToDelete",
      assign: {
        notFound: "apiErrors.admin.inviteCodes.assign.notFound",
        alreadyUsed: "apiErrors.admin.inviteCodes.assign.alreadyUsed",
        expired: "apiErrors.admin.inviteCodes.assign.expired",
        alreadyAssigned: "apiErrors.admin.inviteCodes.assign.alreadyAssigned",
        alreadyIssued: "apiErrors.admin.inviteCodes.assign.alreadyIssued",
        userIdRequired: "apiErrors.admin.inviteCodes.assign.userIdRequired",
        emailRequired: "apiErrors.admin.inviteCodes.assign.emailRequired",
        userNotFound: "apiErrors.admin.inviteCodes.assign.userNotFound",
        notificationsDisabled: "apiErrors.admin.inviteCodes.assign.notificationsDisabled",
      },
    },
    preApplications: {
      failedToFetch: "apiErrors.admin.preApplications.failedToFetch",
      historyFetchFailed: "apiErrors.admin.preApplications.historyFetchFailed",
      failedToReview: "apiErrors.admin.preApplications.failedToReview",
      inviteCodeRequired: "apiErrors.admin.preApplications.inviteCodeRequired",
      invalidInviteExpiry: "apiErrors.admin.preApplications.invalidInviteExpiry",
      expiryMustBeInFuture: "apiErrors.admin.preApplications.expiryMustBeInFuture",
      alreadyReviewed: "apiErrors.admin.preApplications.alreadyReviewed",
      aiNotConfigured: "apiErrors.admin.preApplications.aiNotConfigured",
      aiReviewFailed: "apiErrors.admin.preApplications.aiReviewFailed",
      duplicateCheckFailed: "apiErrors.admin.preApplications.duplicateCheckFailed",
    },
    posts: {
      failedToFetch: "apiErrors.admin.posts.failedToFetch",
      postNotFound: "apiErrors.admin.posts.postNotFound",
      failedToFetchSingle: "apiErrors.admin.posts.failedToFetchSingle",
      failedToUpdate: "apiErrors.admin.posts.failedToUpdate",
      failedToDelete: "apiErrors.admin.posts.failedToDelete",
      failedToCreate: "apiErrors.admin.posts.failedToCreate",
    },
    settings: {
      failedToLoad: "apiErrors.admin.settings.failedToLoad",
      failedToUpdate: "apiErrors.admin.settings.failedToUpdate",
    },
    systemConfig: {
      failedToFetch: "apiErrors.admin.systemConfig.failedToFetch",
      failedToUpdate: "apiErrors.admin.systemConfig.failedToUpdate",
    },
    resetDatabase: {
      failed: "apiErrors.admin.resetDatabase.failed",
    },
    stats: {
      failedToFetch: "apiErrors.admin.stats.failedToFetch",
    },
    emailLogs: {
      failed: "apiErrors.admin.emailLogs.failed",
    },
  },
  dashboard: {
    password: {
      passwordsDoNotMatch: "apiErrors.dashboard.password.passwordsDoNotMatch",
      currentPasswordRequired: "apiErrors.dashboard.password.currentPasswordRequired",
      invalidCurrentPassword: "apiErrors.dashboard.password.invalidCurrentPassword",
      failedToUpdate: "apiErrors.dashboard.password.failedToUpdate",
    },
    messages: {
      failedToFetch: "apiErrors.dashboard.messages.failedToFetch",
      failedToFetchSingle: "apiErrors.dashboard.messages.failedToFetchSingle",
      failedToMarkAsRead: "apiErrors.dashboard.messages.failedToMarkAsRead",
      summary: {
        failedToFetch: "apiErrors.dashboard.messages.summary.failedToFetch",
      },
    },
    posts: {
      failedToFetch: "apiErrors.dashboard.posts.failedToFetch",
      failedToFetchSingle: "apiErrors.dashboard.posts.failedToFetchSingle",
      postNotFound: "apiErrors.dashboard.posts.postNotFound",
      failedToCreate: "apiErrors.dashboard.posts.failedToCreate",
      failedToUpdate: "apiErrors.dashboard.posts.failedToUpdate",
      failedToDelete: "apiErrors.dashboard.posts.failedToDelete",
    },
    profile: {
      failedToUpdate: "apiErrors.dashboard.profile.failedToUpdate",
    },
    account: {
      failedToDelete: "apiErrors.dashboard.account.failedToDelete",
    },
  },
  preApplication: {
    failedToFetch: "apiErrors.preApplication.failedToFetch",
    failedToSubmit: "apiErrors.preApplication.failedToSubmit",
    alreadySubmitted: "apiErrors.preApplication.alreadySubmitted",
    alreadyApproved: "apiErrors.preApplication.alreadyApproved",
    essayTooShort: "apiErrors.preApplication.essayTooShort",
    invalidEmailDomain: "apiErrors.preApplication.invalidEmailDomain",
    sourceDetailRequired: "apiErrors.preApplication.sourceDetailRequired",
    noPreApplicationFound: "apiErrors.preApplication.noPreApplicationFound",
    versionConflict: "apiErrors.preApplication.versionConflict",
    resubmitLimitExceeded: "apiErrors.preApplication.resubmitLimitExceeded",
    failedToUpdate: "apiErrors.preApplication.failedToUpdate",
  },
} as const
